config/routes.rb
Rails.application.routes.draw do
  resources :pages do
    member do
      delete :delete_image_attachment
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  validates :date, presence: true
  has_many_attached :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  http_basic_authenticate_with name: "lexi", password:"gonnaneedbettersecurity", except: [:show]

  def index
    @pages = Page.all.order(:date)
  end

  def show
    @page = Page.find(params[:id])
    @first = Page.order(:date).first()
    @previous = Page.where(["date < ?", @page.date]).order(date: :desc).first()
    @next = Page.where(["date > ?", @page.date]).order(:date).first()
    @last = Page.order(date: :desc).first()
  end

  def new
    @page = Page.new
  end

  def edit
    @page = Page.find(params[:id])
  end

  def create
    @page = Page.new(page_params)

    if @page.save
      redirect_to @page
    else
      render 'new'
    end
  end

  def update
    @page = Page.find(params[:id])

    if @page.update(page_params)
      redirect_to @page
    else
      render 'edit'
    end
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    redirect_to pages_path
  end

  def delete_image_attachment
    @image = ActiveStorage::Attachment.find(params[:attachment_id])
    @image.purge
    redirect_to edit_page_path(params[:page_id])
  end

  private
    def page_params
      params.require(:page).permit(:title, :date, :updated_at, images: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Islife</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with model: @page, local: true do |form| %>
 
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@page.errors.count, "error") %> prohibited
        this page from being saved:
      </h2>
      <ul>
        <% @page.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :date %><br>
    <%= form.date_field :date %>
  </p>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true %>
    <% if @page.images.attached? and not @page.errors.any? %>
      <% @page.images.includes(:blob).references(:blob).order('active_storage_blobs.filename ASC').each do |image| %>
        <%= form.hidden_field :images, multiple: true, value: image.signed_id %>
        <%= image_tag image, class: "img_preview" %>
        <%= image.filename %>
        <%= link_to 'Remove', delete_image_attachment_page_url(attachment_id: image.id, page_id: @page.id),
          method: :delete,
          data: { confirm: 'Are you sure?' } %>
      <% end %>
    <% end %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/pages/edit.html.erb
<h1>Edit Page</h1>
 
<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing Pages</h1>
 
<%= link_to 'Add Page', new_page_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Date</th>
    <th></th>
  </tr>
 
  <% @pages.each do |page| %>
    <tr>
      <td><%= page.title %></td>
      <td><%= page.date %></td>
      <td><%= link_to 'Show', page_path(page) %></td>
      <td><%= link_to 'Edit', edit_page_path(page) %></td>
      <td><%= link_to 'Destroy', page_path(page),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form' %>

app/views/pages/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>
<p>
  <strong>Date:</strong>
  <%= @page.date %>
  <% @page.images.includes(:blob).references(:blob).order('active_storage_blobs.filename ASC').each do |image| %>
    <%= image_tag image, class: "img_preview" %>
    <%= image.filename %>
  <% end %>

  <%= link_to 'First', page_path(@first) %> |
  <% if @previous %>
    <%= link_to 'Prev', page_path(@previous) %> |
  <% else %>
    Prev
  <% end %>
  <%= link_to 'Index', pages_path() %> |
  <%= link_to 'Edit', edit_page_path(@page) %> |
  <% if @next %>
    <%= link_to 'Next', page_path(@next) %> |
  <% else %>
    Next
  <% end %>
  <%= link_to 'Last', page_path(@last) %>
</p>